name: londonmapbot

on:
  schedule:
    - cron: '*/1 * * * *'  # every minute

jobs:
  londonmapbot-post:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Generate and post tweet
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE); lat <- round(runif(1, -0.5, 0.27), 4); lon <- round(runif(1, 51.3, 51.7), 4); img_url <- paste0("https://api.mapbox.com/styles/v1/mapbox/satellite-v9/static/", paste0(lat, ",", lon), ",15,0/600x400@2x?access_token=", "${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}");  rtweet::post_tweet(status = paste0(substr(img_url, nchar(img_url)-5, nchar(img_url)), " // ", lat, ", ", lon), token = rtweet::create_token(app = "londonmapbot", consumer_key = "${{ secrets.TWITTER_CONSUMER_API_KEY }}", consumer_secret = "${{ secrets.TWITTER_CONSUMER_API_SECRET }}", access_token = "${{ secrets.TWITTER_ACCESS_TOKEN }}", access_secret = "${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}"))'
      
