name: remediationbot

#on:
#  schedule:
#      - cron: '10 9-17 * * 1-5'
on:
  push:
    branches:
      - master
      
jobs:
  remediationbot-post:
    runs-on: macOS-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages(c("rtweet","readr", "lubridate", "glue"), dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript remediationbot-tweet.R
